# CRUD SYNTAX
- C: CREATE
- R: READ
- U: UPDATE
- D: DELETE

## CREATE
Create a table in a database.
Once a table is created what follows is inserting the data in a table.

**Syntax:** CREATE TABLE table_name (Attr1 Type1, Attr2 Type2, ...., Attr_n Type_n);

For Example: Create a Table named students with columns name, student_id, course, email, age, gender, bmi. The keys are student_id it's a primary key. name, course are strings, email can be a string though it has its own datatype in databases, gender can be captured as string though it has data type in SQL which boolean.

In [2]:
import sqlite3
import pandas as pd

# Create a database named moringa
moringa_db = sqlite3.connect("moringa.db")

# Establish a connection with the db
# conn = sqlite3.connect("moringa.db")
# conn1 = moringa_db.cursor()

# Create a table named students inside the database
create_tbl_query = """
    CREATE TABLE IF NOT EXISTS students (
        student_id INT PRIMARY KEY NOT NULL,
        name TEXT NOT NULL,
        course TEXT NOT NULL,
        email VARCHAR(50) UNIQUE NOT NULL,
        gender VARCHAR(10) NOT NULL,
        bmi REAL NOT NULL
    );
    """

moringa_db.execute(create_tbl_query)

In [3]:
cur=moringa_db.cursor()

In [4]:
pd.read_sql("SELECT * FROM students", moringa_db)

Empty DataFrame
Columns: [student_id, name, course, email, gender, bmi]
Index: []

Once you create a database, you create tables inside the databases. Then once the tables have been created you can now insert data into your tables. There a command forr inserting data into sql tables known as ***INSERT***.

**Syntax:** INSERT INTO table_name (Attr1, Attr3, Attr2.... Attr_n) VALUES(value1, value3, value2);

In [5]:
# insert_tbl_query = (
#     """
#     INSERT INTO students(name, course, email, gender, bmi)
#         VALUES (?, ?, ?, ?, ?)
#
#     """,
#     [
#         (
#             "Musoke",
#             "Data Science",
#             "musoke.collins@gmail.com",
#             "Male",
#             22.5
#         ),
#         (
#             "Mutheu",
#             "Software Engineering",
#             "mutheu.munene@gmail.com",
#             "Female",
#             20.5
#         ),
#         (
#             "Elvis",
#             "Cyber Security",
#             "elvis.munyao@gmail.com",
#             "Male",
#             21.5
#         ),
#         (
#             "Farhan",
#             "Data Science",
#             "farhan.noor@gmail.com",
#             "Male",
#             22.5
#         )
#     ]
# )
# pd.read_sql(insert_tbl_query, moringa_db)

In [6]:
insert_tbl_query = (
    """
    INSERT INTO students
        (
            student_id,
            name,
            course,
            email,
            gender,
            bmi
        )
    VALUES
    (
        101,
        "Musoke",
        "Data Science",
        "musoke.collins@gmail.com",
        "Male",
        22.5
    ),
    (
        102,
        "Mutheu",
        "Software Engineering",
        "mutheu.munene@gmail.com",
        "Female",
        20.5
    ),
    (
        103,
        "Elvis",
        "Cyber Security",
        "elvis.munyao@gmail.com",
        "Male",
        21.5
    ),
    (
        104,
        "Farhan",
        "Data Science",
        "farhan.noor@gmail.com",
        "Male",
        22.5
    )

    """
)
moringa_db.execute(insert_tbl_query)
moringa_db.commit()

In [7]:
pd.read_sql("SELECT * FROM students", moringa_db)

,student_id,name,course,email,gender,bmi
0,101,Musoke,Data Science,musoke.collins@gmail.com,Male,22.5
1,102,Mutheu,Software Engineering,mutheu.munene@gmail.com,Female,20.5
2,103,Elvis,Cyber Security,elvis.munyao@gmail.com,Male,21.5
3,104,Farhan,Data Science,farhan.noor@gmail.com,Male,22.5

## READ
Retrieving data from a database. It has three clauses:</br></br>
**SELECT:** Gets the attributes required</br>
**FROM:** Refers to the table returning the attributes</br>
**WHERE:** It's a condition to get the attributes based on a specific criteria. It's not compulsory.</br>

**Syntax:** </br> READ attr1, attr2 FROM table_name WHERE condition </br> READ * FROM table_name WHERE condition

In [8]:
# Read all the records from the table

# Read the email of the student with student_id = 3

In [9]:
#Read all records from the table
q=(
    """
    SELECT * FROM students 

    """
   
)
cur.execute(q)
rows= cur.fetchall()
for row in rows:
    
    print(row)

(101, 'Musoke', 'Data Science', 'musoke.collins@gmail.com', 'Male', 22.5)
(102, 'Mutheu', 'Software Engineering', 'mutheu.munene@gmail.com', 'Female', 20.5)
(103, 'Elvis', 'Cyber Security', 'elvis.munyao@gmail.com', 'Male', 21.5)
(104, 'Farhan', 'Data Science', 'farhan.noor@gmail.com', 'Male', 22.5)

In [10]:
# Read the email of the student with student_id = 3
q=("""
SELECT email FROM students
WHERE student_id = 103


""")
cur.execute(q)
result=cur.fetchall()

if not result:
   print("no such student") 
else:
    print(result)

[('elvis.munyao@gmail.com',)]

## UPDATE
Modifying a record/row value inside a table.</br></br>

**Syntax:** UPDATE table_name SET attr1 = value1, attribute2 = value2 WHERE condition

In [11]:
# Update Mutheu's course to data science and her bmi = 23.5
q=("""
UPDATE students 
SET course = "Data science", bmi=23.5
WHERE name= "Mutheu"
""")
cur.execute(q)

In [12]:
pd.read_sql("SELECT * FROM students", moringa_db)

   student_id    name          course                     email  gender   bmi
0         101  Musoke    Data Science  musoke.collins@gmail.com    Male  22.5
1         102  Mutheu    Data science   mutheu.munene@gmail.com  Female  23.5
2         103   Elvis  Cyber Security    elvis.munyao@gmail.com    Male  21.5
3         104  Farhan    Data Science     farhan.noor@gmail.com    Male  22.5

## DELETE
Erasing/Deleting a value inside a table.

**Syntax:** DELETE FROM table_name WHERE condition

In [13]:
# Delete the last student
q=("""
DELETE FROM students
WHERE student_id =104


""")
cur.execute(q)

In [14]:
pd.read_sql("SELECT * FROM students", moringa_db)

   student_id    name          course                     email  gender   bmi
0         101  Musoke    Data Science  musoke.collins@gmail.com    Male  22.5
1         102  Mutheu    Data science   mutheu.munene@gmail.com  Female  23.5
2         103   Elvis  Cyber Security    elvis.munyao@gmail.com    Male  21.5