# Data Analysis With Pandas

## Topics To Be Covered:
Introduction to data analysis using pandas. 

Pandas Dataframes and Series

Data Cleaning using pandas

Aggregating, Reshaping, and Combining Dataframes

## Introduction to data analysis using pandas

What is Data Analysis?
It is the process of examining data to find patterns, answer questions and make decisions. For example a number becomes useful whhen we understand what it measures, a waiting time of 20 means nothing until we know what the unit is in minutes.

Data Science is the field that uses data, statistics, domain knowledge and programming to investigate questions and come up with relevant solutions. Data analysis thus becomes a part of this work.

There are four cmmon types of analysis:
- ***Descriptive analysis:*** It tells us what happened, for example how many patient visits were recorded per clinic.
- ***Diagnostic analysis:*** Tells us why it happened, for example busy patient arrival period might result to longer wait times.
- ***Predictie analysis:*** Tells us what might happen, for eaxmple how many patients might be expected next week.
- ***Prescriptive analysis*** Tells us what should be done or what action should be taken, for eaxmple which staffing plan could reduce patient waiting times.

**Analysis Workflow**
- State a Question
- Get/Obtain/Load the data.
- Inspecting the data: Checking for null values, duplicate values, outliers/extreme values, data types, data size(rows,columns), erroneus values
- Clean the data
- Analyze and Visualize
- Interpret and communicate the results

**Pandas**
- It's a python library for working with tabular data (rows and columns). It can read files, perform data cleaning, aggregation functioons and coombine tables. Its main structure is the ***Series()*** and ***DataFrame()***.

Some of the file formats that Pandas reads are CSV, JSON, EXCEL, SQL.

We install pandas by typing teh following commands:
- In CONDA environments: ***conda install pandas***
- In Python environments: ***pip install pandas***
- Inline inside Jupyter:***! pip install***

## Pandas Series and DataFrames
**Series**
This is a one dimensional labelled collection of values. Think of it as a single column together with its rows

In [67]:
import pandas as pd #pd ia an alias

#Pandas Series
age = pd.Series([22, 34, 27, 44, 19], name = "age")
age

0    22
1    34
2    27
3    44
4    19
Name: age, dtype: int64

In [68]:
temperature = pd.Series([21, 25, 28, 29, 31, 22, 24], index = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], name = "Temperatures")
temperature

Monday       21
Tuesday      25
Wednesday    28
Thursday     29
Friday       31
Saturday     22
Sunday       24
Name: Temperatures, dtype: int64

**DataFrames ** Its a two dimensional labelled table with rows and columns i.e Like an excel sheet which is a collection of multiple series(has multiple rows and multiple columns). For example data that has name , age and height

In [69]:
students = {
    "name": ["John", "Mary", "Peter", "Fridah"],
    "age": [22, 34, 27, 28],
    "county": ["Nairobi", "Mombasa", "Kisumu", "Kirinyaga"],
}
print(students)

df = pd.DataFrame(students)
df

{'name': ['John', 'Mary', 'Peter', 'Fridah'], 'age': [22, 34, 27, 28], 'county': ['Nairobi', 'Mombasa', 'Kisumu', 'Kirinyaga']}

     name  age     county
0    John   22    Nairobi
1    Mary   34    Mombasa
2   Peter   27     Kisumu
3  Fridah   28  Kirinyaga

In [70]:
#TO DO
#1. Assign indexes 101, 102, 103..
df = pd.DataFrame(students, index = [101,102,103,104])
#or
# use df.index([101, 102, 103])
print(df)

#2. Display the number of rows and columns
"""number_of_rows = len(df)
print("Number of rows is : ", number_of_rows)

number_of_columns = len(df.columns)
print("NUmber of columns is : ", number_of_columns)"""


num_cols = df.shape # Gets the length of (rows, columns)
print(num_cols)

#3. Display the column names.

print(df.columns)
#4. Check the data types

print(df.dtypes)

#5. Display the current indexes

print(df.index)

#6. Select one column(name or any of your choice)

print(df["age"])

#7. Select two columns 

#print(df[["age","county"]])
#or
# 
print(df.iloc[:, 0:2])
#8. Select a specific row

print(df.loc[104])

print(df.iloc[3])


#9. Display the third student using their row position
print(df.iloc[2])

#10. Select the first two rows and first two columns.

print(df.iloc[0:2, 0:2])

#11. Display the names and ages of students older than 30

print(df[df["age"]>30][["name", "age"]])


#12. Name the column "name" to "student_name" and "county" to "home_county"

df.rename(columns= {"name": "student_name", "county":"home_county"})

       name  age     county
101    John   22    Nairobi
102    Mary   34    Mombasa
103   Peter   27     Kisumu
104  Fridah   28  Kirinyaga
(4, 3)
Index(['name', 'age', 'county'], dtype='str')
name        str
age       int64
county      str
dtype: object
Index([101, 102, 103, 104], dtype='int64')
101    22
102    34
103    27
104    28
Name: age, dtype: int64
       name  age
101    John   22
102    Mary   34
103   Peter   27
104  Fridah   28
name         Fridah
age              28
county    Kirinyaga
Name: 104, dtype: object
name         Fridah
age              28
county    Kirinyaga
Name: 104, dtype: object
name       Peter
age           27
county    Kisumu
Name: 103, dtype: object
     name  age
101  John   22
102  Mary   34
     name  age
102  Mary   34

    student_name  age home_county
101         John   22     Nairobi
102         Mary   34     Mombasa
103        Peter   27      Kisumu
104       Fridah   28   Kirinyaga

In [71]:
print(df)

       name  age     county
101    John   22    Nairobi
102    Mary   34    Mombasa
103   Peter   27     Kisumu
104  Fridah   28  Kirinyaga