In [297]:
# import pandas library
import pandas as pd 
import numpy as np


#Here, we have also specified that one of the column names (the column ‘name’) will be a unique identifier (or index) for rows in this dataset. 
cereal_df = pd.read_csv("Cereals.csv", index_col= "name")
print(cereal_df)

                          mfr type  calories  protein  fat  sodium  fiber  \
name
100%_Bran                   N    C        70        4    1     130   10.0
100%_Natural_Bran           Q    C       120        3    5      15    2.0
All-Bran                    K    C        70        4    1     260    9.0
All-Bran_with_Extra_Fiber   K    C        50        4    0     140   14.0
Almond_Delight              R    C       110        2    2     200    1.0
...                        ..  ...       ...      ...  ...     ...    ...
Triples                     G    C       110        2    1     250    0.0
Trix                        G    C       110        1    1     140    0.0
Wheat_Chex                  R    C       100        3    1     230    3.0
Wheaties                    G    C       100        3    1     200    3.0
Wheaties_Honey_Gold         G    C       110        2    1     200    1.0

                           carbo  sugars  potass  vitamins  shelf  weight  \
name
100%_Bran                    5.0     6.0   280.0        25      3     1.0
100%_Natural_Bran            8.0     8.0   135.0         0      3     1.0
All-Bran                     7.0     5.0   320.0        25      3     1.0
All-Bran_with_Extra_Fiber    8.0     0.0   330.0        25      3     1.0
Almond_Delight              14.0     8.0     NaN        25      3     1.0
...                          ...     ...     ...       ...    ...     ...
Triples                     21.0     3.0    60.0        25      3     1.0
Trix                        13.0    12.0    25.0        25      2     1.0
Wheat_Chex                  17.0     3.0   115.0        25      1     1.0
Wheaties                    17.0     3.0   110.0        25      1     1.0
Wheaties_Honey_Gold         16.0     8.0    60.0        25      1     1.0

                           cups     rating
name
100%_Bran                  0.33  68.402973
100%_Natural_Bran          1.00  33.983679
All-Bran                   0.33  59.425505
All-Bran_with_Extra_Fiber  0.50  93.704912
Almond_Delight             0.75  34.384843
...                         ...        ...
Triples                    0.75  39.106174
Trix                       1.00  27.753301
Wheat_Chex                 0.67  49.787445
Wheaties                   1.00  51.592193
Wheaties_Honey_Gold        0.75  36.187559

[77 rows x 15 columns]

The .info() method outputs column names, the data type for each column, non-null counts.

In [298]:
cereal_df.info()

<class 'pandas.DataFrame'>
Index: 77 entries, 100%_Bran to Wheaties_Honey_Gold
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mfr       77 non-null     str
 1   type      77 non-null     str
 2   calories  77 non-null     int64
 3   protein   77 non-null     int64
 4   fat       77 non-null     int64
 5   sodium    77 non-null     int64
 6   fiber     77 non-null     float64
 7   carbo     76 non-null     float64
 8   sugars    76 non-null     float64
 9   potass    75 non-null     float64
 10  vitamins  77 non-null     int64
 11  shelf     77 non-null     int64
 12  weight    77 non-null     float64
 13  cups      77 non-null     float64
 14  rating    77 non-null     float64
dtypes: float64(7), int64(6), str(2)
memory usage: 10.9 KB

.describe() method: statistics for each column.

In [299]:
cereal_df.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,77.000000,77.000000,77.000000,77.000000,77.000000,76.000000,76.000000,75.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,106.883117,2.545455,1.012987,159.675325,2.151948,14.802632,7.026316,98.666667,28.246753,2.207792,1.029610,0.821039,42.665705
std,19.484119,1.094790,1.006473,83.832295,2.383364,3.907326,4.378656,70.410636,22.342523,0.832524,0.150477,0.232716,14.047289
min,50.000000,1.000000,0.000000,0.000000,0.000000,5.000000,0.000000,15.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,130.000000,1.000000,12.000000,3.000000,42.500000,25.000000,1.000000,1.000000,0.670000,33.174094
50%,110.000000,3.000000,1.000000,180.000000,2.000000,14.500000,7.000000,90.000000,25.000000,2.000000,1.000000,0.750000,40.400208
75%,110.000000,3.000000,2.000000,210.000000,3.000000,17.000000,11.000000,120.000000,25.000000,3.000000,1.000000,1.000000,50.828392
max,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.500000,93.704912

DataFrame.index: list of index names for row

In [300]:
cereal_df.index[0:10]

Index(['100%_Bran', '100%_Natural_Bran', 'All-Bran',
       'All-Bran_with_Extra_Fiber', 'Almond_Delight',
       'Apple_Cinnamon_Cheerios', 'Apple_Jacks', 'Basic_4', 'Bran_Chex',
       'Bran_Flakes'],
      dtype='str', name='name')

DataFrame.columns: list of column name

In [301]:
cereal_df.columns

Index(['mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber', 'carbo',
       'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups', 'rating'],
      dtype='str')

DataFrame.shape: returns (number rows, number columns) tuple

In [302]:
cereal_df.shape

(77, 15)

For DataFrames, you can access entire columns in a similar way. Let’s access the calories column.

Note that this is returning a Series with the name "calories". This is because individual columns/rows are extracted as pandas Series from the DataFrame architecture.

In [303]:
cereal_df['calories']

name
100%_Bran                     70
100%_Natural_Bran            120
All-Bran                      70
All-Bran_with_Extra_Fiber     50
Almond_Delight               110
                            ...
Triples                      110
Trix                         110
Wheat_Chex                   100
Wheaties                     100
Wheaties_Honey_Gold          110
Name: calories, Length: 77, dtype: int64

You can also extract data from a subset of the columns by passing in a list of column names.

DataFrame[list of column names in subset]: returns a DataFrame

In [304]:
col_list = ["calories", "fat", "sugars", "protein"]
cereal_df[col_list]

#This is a new dataframe with just the accessed columns in the list.

                           calories  fat  sugars  protein
name
100%_Bran                        70    1     6.0        4
100%_Natural_Bran               120    5     8.0        3
All-Bran                         70    1     5.0        4
All-Bran_with_Extra_Fiber        50    0     0.0        4
Almond_Delight                  110    2     8.0        2
...                             ...  ...     ...      ...
Triples                         110    1     3.0        2
Trix                            110    1    12.0        1
Wheat_Chex                      100    1     3.0        3
Wheaties                        100    1     3.0        3
Wheaties_Honey_Gold             110    1     8.0        2

[77 rows x 4 columns]

We can access a particular row and column as follows:

DataFrame[column_name][row_name]

In [305]:
cereal_df["sugars"]["Trix"]

np.float64(12.0)

We have just seen how to access data, but now we would like to be able access a single row or even a particular item within a Pandas DataFrame by using the .loc[] accessor.

The .loc[] accessor:

Easily access single row in a DataFrame by named index.
Allows for complex selections: enables slicing on index labels across both rows and columns.
Really important to use when assigning values to a selection; we will see this later.
The general pattern for .loc[] accessor is:

DataFrame.loc[row_accessor]
DataFrame.loc[row_accessor, column_accessor]

To see how we can access a single row with .loc[], let’s select the cereal All-Bran:

In [306]:
cereal_df.loc["Wheat_Chex"]

mfr                 R
type                C
calories          100
protein             3
fat                 1
sodium            230
fiber             3.0
carbo            17.0
sugars            3.0
potass          115.0
vitamins           25
shelf               1
weight            1.0
cups             0.67
rating      49.787445
Name: Wheat_Chex, dtype: object

We can also select rows by passing in a list of index names to the row accessor.

In [307]:
cereal_list = ["Cocoa_Puffs", "Froot_Loops", "Honey-comb"]
cereal_df.loc[cereal_list]

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
Cocoa_Puffs,G,C,110,1,1,180,0.0,12.0,13.0,55.0,25,2,1.0,1.00,22.736446
Froot_Loops,K,C,110,2,1,125,1.0,11.0,13.0,30.0,25,2,1.0,1.00,32.207582
Honey-comb,P,C,110,1,0,180,0.0,14.0,11.0,35.0,25,1,1.0,1.33,28.742414

Pandas also allows slicing on row indices. The slicing on the named index with the .loc[] accessor is inclusive of start and end labels.

In [308]:
# slice rows by name

cereal_df.loc["Cap'n'Crunch" : "Puffed_Rice"]

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,12.0,35.0,25,2,1.00,0.75,18.042851
Cheerios,G,C,110,6,2,290,2.0,17.0,1.0,105.0,25,1,1.00,1.25,50.764999
Cinnamon_Toast_Crunch,G,C,120,1,3,210,0.0,13.0,9.0,45.0,25,2,1.00,0.75,19.823573
Clusters,G,C,110,3,2,140,2.0,13.0,7.0,105.0,25,3,1.00,0.50,40.400208
Cocoa_Puffs,G,C,110,1,1,180,0.0,12.0,13.0,55.0,25,2,1.00,1.00,22.736446
Corn_Chex,R,C,110,2,0,280,0.0,22.0,3.0,25.0,25,1,1.00,1.00,41.445019
Corn_Flakes,K,C,100,2,0,290,1.0,21.0,2.0,35.0,25,1,1.00,1.00,45.863324
Corn_Pops,K,C,110,1,0,90,1.0,13.0,12.0,20.0,25,2,1.00,1.00,35.782791
Count_Chocula,G,C,110,1,1,180,0.0,12.0,13.0,65.0,25,2,1.00,1.00,22.396513
Cracklin'_Oat_Bran,K,C,110,3,3,140,4.0,10.0,7.0,160.0,25,3,1.00,0.50,40.448772
Cream_of_Wheat_(Quick),N,H,100,3,0,80,1.0,21.0,0.0,NaN,0,2,1.00,1.00,64.533816
Crispix,K,C,110,2,0,220,1.0,21.0,3.0,30.0,25,3,1.00,1.00,46.895644
Crispy_Wheat_&_Raisins,G,C,100,2,1,140,2.0,11.0,10.0,120.0,25,3,1.00,0.75,36.176196
Double_Chex,R,C,100,2,0,190,1.0,18.0,5.0,80.0,25,3,1.00,0.75,44.330856
Froot_Loops,K,C,110,2,1,125,1.0,11.0,13.0,30.0,25,2,1.00,1.00,32.207582
Frosted_Flakes,K,C,110,1,0,200,1.0,14.0,11.0,25.0,25,1,1.00,0.75,31.435973
Frosted_Mini-Wheats,K,C,100,3,0,0,3.0,14.0,7.0,100.0,25,2,1.00,0.80,58.345141
"Fruit_&_Fibre_Dates,_Walnuts,_and_Oats",P,C,120,3,2,160,5.0,12.0,10.0,200.0,25,3,1.25,0.67,40.917047
Fruitful_Bran,K,C,120,3,0,240,5.0,14.0,12.0,190.0,25,3,1.33,0.67,41.015492
Fruity_Pebbles,P,C,110,1,1,135,0.0,13.0,12.0,25.0,25,2,1.00,0.75,28.025765
Golden_Crisp,P,C,100,2,0,45,0.0,11.0,15.0,40.0,25,1,1.00,0.88,35.252444
Golden_Grahams,G,C,110,1,1,280,0.0,15.0,9.0,45.0,25,2,1.00,0.75,23.804043
Grape_Nuts_Flakes,P,C,100,3,1,140,3.0,15.0,5.0,85.0,25,3,1.00,0.88,52.076897
Grape-Nuts,P,C,110,3,0,170,3.0,17.0,3.0,90.0,25,3,1.00,0.25,53.371007
Great_Grains_Pecan,P,C,120,3,3,75,3.0,13.0,4.0,100.0,25,3,1.00,0.33,45.811716
Honey_Graham_Ohs,Q,C,120,1,2,220,1.0,12.0,11.0,45.0,25,2,1.00,1.00,21.871292
Honey_Nut_Cheerios,G,C,110,3,1,250,1.5,11.5,10.0,90.0,25,1,1.00,0.75,31.072217
Honey-comb,P,C,110,1,0,180,0.0,14.0,11.0,35.0,25,1,1.00,1.33,28.742414
Just_Right_Crunchy__Nuggets,K,C,110,2,1,170,1.0,17.0,6.0,60.0,100,3,1.00,1.00,36.523683
Just_Right_Fruit_&_Nut,K,C,140,3,1,170,2.0,20.0,9.0,95.0,100,3,1.30,0.75,36.471512
Kix,G,C,110,2,1,260,0.0,21.0,3.0,40.0,25,2,1.00,1.50,39.241114
Life,Q,C,100,4,2,150,2.0,12.0,6.0,95.0,25,2,1.00,0.67,45.328074
Lucky_Charms,G,C,110,2,1,180,0.0,12.0,12.0,55.0,25,2,1.00,1.00,26.734515
Maypo,A,H,100,4,1,0,0.0,16.0,3.0,95.0,25,2,1.00,1.00,54.850917
"Muesli_Raisins,_Dates,_&_Almonds",R,C,150,4,3,95,3.0,16.0,11.0,170.0,25,3,1.00,1.00,37.136863
"Muesli_Raisins,_Peaches,_&_Pecans",R,C,150,4,3,150,3.0,16.0,11.0,170.0,25,3,1.00,1.00,34.139765
Mueslix_Crispy_Blend,K,C,160,3,2,150,3.0,17.0,13.0,160.0,25,3,1.50,0.67,30.313351
Multi-Grain_Cheerios,G,C,100,2,1,220,2.0,15.0,6.0,90.0,25,1,1.00,1.00,40.105965
Nut&Honey_Crunch,K,C,120,2,1,190,0.0,15.0,9.0,40.0,25,2,1.00,0.67,29.924285
Nutri-Grain_Almond-Raisin,K,C,140,3,2,220,3.0,21.0,7.0,130.0,25,3,1.33,0.67,40.692320
Nutri-grain_Wheat,K,C,90,3,0,170,3.0,18.0,2.0,90.0,25,3,1.00,1.00,59.642837
Oatmeal_Raisin_Crisp,G,C,130,3,2,170,1.5,13.5,10.0,120.0,25,3,1.25,0.50,30.450843
Post_Nat._Raisin_Bran,P,C,120,3,1,200,6.0,11.0,14.0,260.0,25,3,1.33,0.67,37.840594
Product_19,K,C,100,3,0,320,1.0,20.0,3.0,45.0,100,3,1.00,1.00,41.503540
Puffed_Rice,Q,C,50,1,0,0,0.0,13.0,0.0,15.0,0,3,0.50,1.00,60.756112

Accessing multiple columns at the same time as selecting a row can be done by passing a list into the column part of the accessor. Let us say that we wanted calories, protein, fat, and sodium information for the cereal All-Bran.

In [309]:
# select columns by list

columns_list = ["sodium", "potass", "weight"]
cereal_df.loc["Cap'n'Crunch" : "Puffed_Rice", columns_list]

                                        sodium  potass  weight
name
Cap'n'Crunch                               220    35.0    1.00
Cheerios                                   290   105.0    1.00
Cinnamon_Toast_Crunch                      210    45.0    1.00
Clusters                                   140   105.0    1.00
Cocoa_Puffs                                180    55.0    1.00
Corn_Chex                                  280    25.0    1.00
Corn_Flakes                                290    35.0    1.00
Corn_Pops                                   90    20.0    1.00
Count_Chocula                              180    65.0    1.00
Cracklin'_Oat_Bran                         140   160.0    1.00
Cream_of_Wheat_(Quick)                      80     NaN    1.00
Crispix                                    220    30.0    1.00
Crispy_Wheat_&_Raisins                     140   120.0    1.00
Double_Chex                                190    80.0    1.00
Froot_Loops                                125    30.0    1.00
Frosted_Flakes                             200    25.0    1.00
Frosted_Mini-Wheats                          0   100.0    1.00
Fruit_&_Fibre_Dates,_Walnuts,_and_Oats     160   200.0    1.25
Fruitful_Bran                              240   190.0    1.33
Fruity_Pebbles                             135    25.0    1.00
Golden_Crisp                                45    40.0    1.00
Golden_Grahams                             280    45.0    1.00
Grape_Nuts_Flakes                          140    85.0    1.00
Grape-Nuts                                 170    90.0    1.00
Great_Grains_Pecan                          75   100.0    1.00
Honey_Graham_Ohs                           220    45.0    1.00
Honey_Nut_Cheerios                         250    90.0    1.00
Honey-comb                                 180    35.0    1.00
Just_Right_Crunchy__Nuggets                170    60.0    1.00
Just_Right_Fruit_&_Nut                     170    95.0    1.30
Kix                                        260    40.0    1.00
Life                                       150    95.0    1.00
Lucky_Charms                               180    55.0    1.00
Maypo                                        0    95.0    1.00
Muesli_Raisins,_Dates,_&_Almonds            95   170.0    1.00
Muesli_Raisins,_Peaches,_&_Pecans          150   170.0    1.00
Mueslix_Crispy_Blend                       150   160.0    1.50
Multi-Grain_Cheerios                       220    90.0    1.00
Nut&Honey_Crunch                           190    40.0    1.00
Nutri-Grain_Almond-Raisin                  220   130.0    1.33
Nutri-grain_Wheat                          170    90.0    1.00
Oatmeal_Raisin_Crisp                       170   120.0    1.25
Post_Nat._Raisin_Bran                      200   260.0    1.33
Product_19                                 320    45.0    1.00
Puffed_Rice                                  0    15.0    0.50

Step 8: Selections on Rows and Columns
Let’s slice on rows and columns to get all cereals from All-Bran to Almond Delight with columns from calories to sodium:

In [310]:
cereal_df.loc["Fruity_Pebbles": "Multi-Grain_Cheerios", "type": "shelf"]

,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf
name,,,,,,,,,,,
Fruity_Pebbles,C,110,1,1,135,0.0,13.0,12.0,25.0,25,2
Golden_Crisp,C,100,2,0,45,0.0,11.0,15.0,40.0,25,1
Golden_Grahams,C,110,1,1,280,0.0,15.0,9.0,45.0,25,2
Grape_Nuts_Flakes,C,100,3,1,140,3.0,15.0,5.0,85.0,25,3
Grape-Nuts,C,110,3,0,170,3.0,17.0,3.0,90.0,25,3
Great_Grains_Pecan,C,120,3,3,75,3.0,13.0,4.0,100.0,25,3
Honey_Graham_Ohs,C,120,1,2,220,1.0,12.0,11.0,45.0,25,2
Honey_Nut_Cheerios,C,110,3,1,250,1.5,11.5,10.0,90.0,25,1
Honey-comb,C,110,1,0,180,0.0,14.0,11.0,35.0,25,1
Just_Right_Crunchy__Nuggets,C,110,2,1,170,1.0,17.0,6.0,60.0,100,3
Just_Right_Fruit_&_Nut,C,140,3,1,170,2.0,20.0,9.0,95.0,100,3
Kix,C,110,2,1,260,0.0,21.0,3.0,40.0,25,2
Life,C,100,4,2,150,2.0,12.0,6.0,95.0,25,2
Lucky_Charms,C,110,2,1,180,0.0,12.0,12.0,55.0,25,2
Maypo,H,100,4,1,0,0.0,16.0,3.0,95.0,25,2
"Muesli_Raisins,_Dates,_&_Almonds",C,150,4,3,95,3.0,16.0,11.0,170.0,25,3
"Muesli_Raisins,_Peaches,_&_Pecans",C,150,4,3,150,3.0,16.0,11.0,170.0,25,3
Mueslix_Crispy_Blend,C,160,3,2,150,3.0,17.0,13.0,160.0,25,3
Multi-Grain_Cheerios,C,100,2,1,220,2.0,15.0,6.0,90.0,25,1

We can also use the .loc[] accessor to get all rows “:” and a column subset. For example, if I wanted just the protein and fat data for all cereals:

In [311]:
cereal_df.loc[:, ["protein", "fat"]]

                           protein  fat
name
100%_Bran                        4    1
100%_Natural_Bran                3    5
All-Bran                         4    1
All-Bran_with_Extra_Fiber        4    0
Almond_Delight                   2    2
...                            ...  ...
Triples                          2    1
Trix                             1    1
Wheat_Chex                       3    1
Wheaties                         3    1
Wheaties_Honey_Gold              2    1

[77 rows x 2 columns]

We can also use the .loc[] accessor to get all rows “:” and a column subset. For example, if I wanted just the protein and fat data for all cereals:

Using the .iloc[] accessor we can slice rows and columns by positional index. The positional indices are zero-indexed and the last index is NOT included in the slice. 

If we want to access the rows between 100% Natural Bran and All-Bran with Extra Fiber and columns from calories to sodium with the .iloc[] accessor:

In [312]:
cereal_df.iloc[1:4, 2:6]

                           calories  protein  fat  sodium
name
100%_Natural_Bran               120        3    5      15
All-Bran                         70        4    1     260
All-Bran_with_Extra_Fiber        50        4    0     140

Step 9: Changing Attributes and Values with Pandas
There are a few ways in which you will want to modify a DataFrame you have imported or Series you have created:

Cleaning and altering column/index names
Creating and removing columns/rows
Altering values
Changing data types
Let's walk through how to do all of these. Let's take a look at the column names with the .column DataFrame attribute:

In [313]:
cereal_df.columns

Index(['mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber', 'carbo',
       'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups', 'rating'],
      dtype='str')

Renaming columns
Some of these names (e.g. "mfr") are abbreviated. Let's say we want to rename some of these columns to their full name:

DataFrame.rename(columns = ___)
columns takes in a dict that maps column names.

Dataframe.rename() method creates a new dataframe by default. We need to reassign our original DataFrame to reflect these changes i.e. actually assign or save them in the  `cereal_df` variable.

In [314]:
cereal_df = cereal_df.rename(columns = {'mfr': 'manufacturer', 'carbo': 'carbohydate', 'potass': 'potassium  '})
cereal_df

,manufacturer,type,calories,protein,fat,sodium,fiber,carbohydate,sugars,potassium,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,3,1.0,0.33,59.425505
All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.0,0.50,93.704912
Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,25,3,1.0,0.75,39.106174
Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,25,2,1.0,1.00,27.753301
Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,25,1,1.0,0.67,49.787445
Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,25,1,1.0,1.00,51.592193
Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,25,1,1.0,0.75,36.187559

You could alternatively just use the (inplace = ... argument) so that it modifies the DataFrame in place (in this case variable assignment isn’t necessary).

In [315]:
cereal_df.rename(columns = {'mfr': 'manufacturer', 'carbo': 'carbohydate', 'potass': 'potassium  '}, inplace = True)
cereal_df.head(2)

,manufacturer,type,calories,protein,fat,sodium,fiber,carbohydate,sugars,potassium,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.0,0.33,68.402973
100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,3,1.0,1.00,33.983679

We accidently introduce trailing white space into the column name. Many imports from files have this problem.

What string command do we need to trim white space? Use .strip() with list comprehension.

In [316]:
[col.strip() for col in cereal_df.columns]

['manufacturer',
 'type',
 'calories',
 'protein',
 'fat',
 'sodium',
 'fiber',
 'carbohydate',
 'sugars',
 'potassium',
 'vitamins',
 'shelf',
 'weight',
 'cups',
 'rating']

It's generally better to use Pandas native vectorized str methods as these are faster and use less code:

In [317]:
cereal_df.columns = cereal_df.columns.str.strip()
print(cereal_df.columns)

Index(['manufacturer', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbohydate', 'sugars', 'potassium', 'vitamins', 'shelf', 'weight',
       'cups', 'rating'],
      dtype='str')

Removing and Creating New Columns
Let’s practice removing a column and in particular the shelf column shelf in the cereal aisle of a particular grocery store.

Let's say we don't care about this column. We will drop it with the .drop() command specifying columns to be dropped. We specify the in-place = True argument so that the changes are applied to the original dataframe:

In [318]:
cereal_df.drop(columns = ['shelf'], inplace = True)
cereal_df.columns

Index(['manufacturer', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbohydate', 'sugars', 'potassium', 'vitamins', 'weight', 'cups',
       'rating'],
      dtype='str')

So that’s removing a column, how do we create a new column?

The 'type' column has only two unique entries 'C' and 'H' (cold or hot cereal?). We can use Boolean condition to create a series and then encode it by integer.

Is this a hot cereal? Convert Boolean to integer.

False = 0
True = 1
N.B. In general, this only works appropriately for a column with two distinct values. In the case where there are more than two distinct values, the code below will encode one of the values as 1 and the rest as 0.

In [319]:
#astype converts the Boolean series to int
is_hot = (cereal_df.type == 'H').astype('int') 
print(is_hot)
print(is_hot.value_counts())

name
100%_Bran                    0
100%_Natural_Bran            0
All-Bran                     0
All-Bran_with_Extra_Fiber    0
Almond_Delight               0
                            ..
Triples                      0
Trix                         0
Wheat_Chex                   0
Wheaties                     0
Wheaties_Honey_Gold          0
Name: type, Length: 77, dtype: int64
type
0    74
1     3
Name: count, dtype: int64

Store this as a new column by:

DataFrame[new_column_name] = series

In [320]:
cereal_df['is_hot'] = is_hot
cereal_df.tail(10)

,manufacturer,type,calories,protein,fat,sodium,fiber,carbohydate,sugars,potassium,vitamins,weight,cups,rating,is_hot
name,,,,,,,,,,,,,,,
Special_K,K,C,110,6,0,230,1.0,16.0,3.0,55.0,25,1.0,1.00,53.131324,0
Strawberry_Fruit_Wheats,N,C,90,2,0,15,3.0,15.0,5.0,90.0,25,1.0,1.00,59.363993,0
Total_Corn_Flakes,G,C,110,2,1,200,0.0,21.0,3.0,35.0,100,1.0,1.00,38.839746,0
Total_Raisin_Bran,G,C,140,3,1,190,4.0,15.0,14.0,230.0,100,1.5,1.00,28.592785,0
Total_Whole_Grain,G,C,100,3,1,200,3.0,16.0,3.0,110.0,100,1.0,1.00,46.658844,0
Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,25,1.0,0.75,39.106174,0
Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,25,1.0,1.00,27.753301,0
Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,25,1.0,0.67,49.787445,0
Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,25,1.0,1.00,51.592193,0
Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,25,1.0,0.75,36.187559,0

Step 10: Dealing with the Index and Alternating Series & DataFrames
Dealing with index, rows, and columns
Let’s now see how we can deal with the index, columns, and rows.

Sometimes we want to reset the index, which takes the index to a column again. The dataframe index will then be integer-indexed.

In [321]:
cereal_df.reset_index(inplace = True)
cereal_df.head()

,name,manufacturer,type,calories,protein,fat,sodium,fiber,carbohydate,sugars,potassium,vitamins,weight,cups,rating,is_hot
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,1.0,0.33,68.402973,0
1,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,1.0,1.00,33.983679,0
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,1.0,0.33,59.425505,0
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,1.0,0.50,93.704912,0
4,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,1.0,0.75,34.384843,0

In [322]:
cereal_df.index

RangeIndex(start=0, stop=77, step=1)

Since we have manipulated the columns and rows and we’d like to perform further analysis, we will now use a command similar to reset_index(), which is set_index. This will allow us to remove the “All-Bran” cereal. This will allow us to remove the “All-Bran” cereal after setting the index.

The 'name' column should be our index

.set_index(col_name) will set that column to the row index.
.set_index() can also take in a list or an index object.

In [323]:
cereal_df.set_index("name", inplace=True)
cereal_df.head(5)

,manufacturer,type,calories,protein,fat,sodium,fiber,carbohydate,sugars,potassium,vitamins,weight,cups,rating,is_hot
name,,,,,,,,,,,,,,,
100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,1.0,0.33,68.402973,0
100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,1.0,1.00,33.983679,0
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,1.0,0.33,59.425505,0
All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,1.0,0.50,93.704912,0
Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,1.0,0.75,34.384843,0

Checking the index we see that the ‘name’ column is now our DataFrame index:

In [324]:
cereal_df.index

Index(['100%_Bran', '100%_Natural_Bran', 'All-Bran',
       'All-Bran_with_Extra_Fiber', 'Almond_Delight',
       'Apple_Cinnamon_Cheerios', 'Apple_Jacks', 'Basic_4', 'Bran_Chex',
       'Bran_Flakes', 'Cap'n'Crunch', 'Cheerios', 'Cinnamon_Toast_Crunch',
       'Clusters', 'Cocoa_Puffs', 'Corn_Chex', 'Corn_Flakes', 'Corn_Pops',
       'Count_Chocula', 'Cracklin'_Oat_Bran', 'Cream_of_Wheat_(Quick)',
       'Crispix', 'Crispy_Wheat_&_Raisins', 'Double_Chex', 'Froot_Loops',
       'Frosted_Flakes', 'Frosted_Mini-Wheats',
       'Fruit_&_Fibre_Dates,_Walnuts,_and_Oats', 'Fruitful_Bran',
       'Fruity_Pebbles', 'Golden_Crisp', 'Golden_Grahams', 'Grape_Nuts_Flakes',
       'Grape-Nuts', 'Great_Grains_Pecan', 'Honey_Graham_Ohs',
       'Honey_Nut_Cheerios', 'Honey-comb', 'Just_Right_Crunchy__Nuggets',
       'Just_Right_Fruit_&_Nut', 'Kix', 'Life', 'Lucky_Charms', 'Maypo',
       'Muesli_Raisins,_Dates,_&_Almonds', 'Muesli_Raisins,_Peaches,_&_Pecans',
       'Mueslix_Crispy_Blend', 'Multi-Grain_Cheerios', 'Nut&Honey_Crunch',
       'Nutri-Grain_Almond-Raisin', 'Nutri-grain_Wheat',
       'Oatmeal_Raisin_Crisp', 'Post_Nat._Raisin_Bran', 'Product_19',
       'Puffed_Rice', 'Puffed_Wheat', 'Quaker_Oat_Squares', 'Quaker_Oatmeal',
       'Raisin_Bran', 'Raisin_Nut_Bran', 'Raisin_Squares', 'Rice_Chex',
       'Rice_Krispies', 'Shredded_Wheat', 'Shredded_Wheat_'n'Bran',
       'Shredded_Wheat_spoon_size', 'Smacks', 'Special_K',
       'Strawberry_Fruit_Wheats', 'Total_Corn_Flakes', 'Total_Raisin_Bran',
       'Total_Whole_Grain', 'Triples', 'Trix', 'Wheat_Chex', 'Wheaties',
       'Wheaties_Honey_Gold'],
      dtype='str', name='name')

We can also drop rows by index name. Let’s drop the cereal All-Bran:

In [325]:
allbrandropped = cereal_df.drop("All-Bran")

allbrandropped

,manufacturer,type,calories,protein,fat,sodium,fiber,carbohydate,sugars,potassium,vitamins,weight,cups,rating,is_hot
name,,,,,,,,,,,,,,,
100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,1.0,0.33,68.402973,0
100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,1.0,1.00,33.983679,0
All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,1.0,0.50,93.704912,0
Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,25,1.0,0.75,34.384843,0
Apple_Cinnamon_Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,25,1.0,0.75,29.509541,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,25,1.0,0.75,39.106174,0
Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,25,1.0,1.00,27.753301,0
Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,25,1.0,0.67,49.787445,0
Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,25,1.0,1.00,51.592193,0
Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,25,1.0,0.75,36.187559,0

The .drop command can drop multiple rows by taking in a list of indices. Let’s drop the cereals '100% Bran' and 'Almond Delight':

In [326]:
two_dropped = cereal_df.drop(["100%_Bran","Almond_Delight"])
two_dropped

,manufacturer,type,calories,protein,fat,sodium,fiber,carbohydate,sugars,potassium,vitamins,weight,cups,rating,is_hot
name,,,,,,,,,,,,,,,
100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,0,1.0,1.00,33.983679,0
All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,25,1.0,0.33,59.425505,0
All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,1.0,0.50,93.704912,0
Apple_Cinnamon_Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.0,25,1.0,0.75,29.509541,0
Apple_Jacks,K,C,110,2,0,125,1.0,11.0,14.0,30.0,25,1.0,1.00,33.174094,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.0,25,1.0,0.75,39.106174,0
Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.0,25,1.0,1.00,27.753301,0
Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.0,25,1.0,0.67,49.787445,0
Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.0,25,1.0,1.00,51.592193,0
Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.0,25,1.0,0.75,36.187559,0

Altering dataframe/series values
It's really important to use the .loc[] accessor when assigning data to dataframe/series selections.

Let’s see why with this example. Select all cold cereals and look at their rating:

In [327]:
cereal_df.loc[cereal_df["type"]== "C", "rating"] +=5
cereal_df.loc[cereal_df["type"] == "C", "rating"]

name
100%_Bran                    73.402973
100%_Natural_Bran            38.983679
All-Bran                     64.425505
All-Bran_with_Extra_Fiber    98.704912
Almond_Delight               39.384843
                               ...
Triples                      44.106174
Trix                         32.753301
Wheat_Chex                   54.787445
Wheaties                     56.592193
Wheaties_Honey_Gold          41.187559
Name: rating, Length: 74, dtype: float64

Step 11: Descriptive Statistics and Applying Functions in Pandas
Descriptive statistics are among the most essential aspects of data science and we also need to be able to apply functions. We need to see how we can do this in Pandas when we have a series or a DataFrame. Thus, let’s:

Calculate summary statistics for a series or a subset of a DataFrame.
Apply a function to a pandas series or DataFrame.
Let's look at the canonical Titanic passenger dataset.

In [328]:
import pandas as pd

titanic_test_df = pd.read_csv("titanic_test.csv")
titanic_train_df = pd.read_csv("titanic_train.csv")

print(titanic_test_df.head())
print("\n\n\n\n\n")
print(titanic_train_df.head())

   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked
0  34.5      0      0   330911   7.8292   NaN        Q
1  47.0      1      0   363272   7.0000   NaN        S
2  62.0      0      0   240276   9.6875   NaN        Q
3  27.0      0      0   315154   8.6625   NaN        S
4  22.0      1      1  3101298  12.2875   NaN        S






   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [329]:
titanic_test_df.info()
print("\n\n\n\n\n")
titanic_train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 52.8 KB






<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [330]:
titanic_train_df.drop(columns="PassengerId", inplace=True)
titanic_train_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Calculating Column Statistics
For columns, we often are interested in calculating a particular statistic for one or a few columns. Happily, DataFrames and Series objects have many built-in methods that can calculate these summary statistics.

First, we can use the .select_dtypes() method to select columns from a DataFrame of a particular data type. Here we will insist that the columns we extract are numeric only. This can be by passing in the 'number' string to include keyword argument.

In [331]:
df_numeric = titanic_train_df.select_dtypes(include="number")
df_numeric

     Survived  Pclass   Age  SibSp  Parch     Fare
0           0       3  22.0      1      0   7.2500
1           1       1  38.0      1      0  71.2833
2           1       3  26.0      0      0   7.9250
3           1       1  35.0      1      0  53.1000
4           0       3  35.0      0      0   8.0500
..        ...     ...   ...    ...    ...      ...
886         0       2  27.0      0      0  13.0000
887         1       1  19.0      0      0  30.0000
888         0       3   NaN      1      2  23.4500
889         1       1  26.0      0      0  30.0000
890         0       3  32.0      0      0   7.7500

[891 rows x 6 columns]

The general pattern for calculating a statistic across many columns of a DataFrame or for a particular column (i.e. a Series) goes as follows:

DataFrame.particular_statistic()
Series.particular_statistic()
Let's do this for the mean.

If we want to calculate the mean across these columns:

In [332]:
df_numeric.mean()

Survived     0.383838
Pclass       2.308642
Age         29.699118
SibSp        0.523008
Parch        0.381594
Fare        32.204208
dtype: float64

Mean
Calculating the mean for a particular column, where across a Series is the same syntax):

In [333]:
df_numeric["Fare"].mean()

np.float64(32.204207968574636)

The pattern is the same for statistics like the median, calculating percentiles, or the standard deviation, which should all remind you of numpy syntax.

In [334]:
df_numeric["Age"].median()

np.float64(28.0)

In [335]:
df_numeric.std(ddof=1)

Survived     0.486592
Pclass       0.836071
Age         14.526497
SibSp        1.102743
Parch        0.806057
Fare        49.693429
dtype: float64

In [336]:
q1 = df_numeric["Age"].quantile(0.25)
q2 = df_numeric["Age"].quantile(0.50)
q3 = df_numeric["Age"].quantile(0.75)
q4 = df_numeric["Age"].quantile(1)
iqr = q3 - q1

print(q1, q2, q3, q4, iqr)

20.125 28.0 38.0 80.0 17.875

Other important statistics
Here other important descriptive statistics that you should be familiar with:

.mode() -- the mode of the column
.count() -- the count of the total number of entries in a column
.var() -- the variance for the column
.sum() -- the sum of all values in the column
.cumsum() -- the cumulative sum, where each cell index contains the sum of all indices lower than, and including, itself

In [337]:
df_numeric.mode()

   Survived  Pclass   Age  SibSp  Parch  Fare
0         0       3  24.0      0      0  8.05

In [338]:
df_numeric.count()

Survived    891
Pclass      891
Age         714
SibSp       891
Parch       891
Fare        891
dtype: int64

In [339]:
df_numeric.cumsum()

     Survived  Pclass       Age  SibSp  Parch        Fare
0           0       3     22.00      1      0      7.2500
1           1       4     60.00      2      0     78.5333
2           2       7     86.00      2      0     86.4583
3           3       8    121.00      3      0    139.5583
4           3      11    156.00      3      0    147.6083
..        ...     ...       ...    ...    ...         ...
886       340    2049  21128.17    465    338  28602.7493
887       341    2050  21147.17    465    338  28632.7493
888       341    2053       NaN    466    340  28656.1993
889       342    2054  21173.17    466    340  28686.1993
890       342    2057  21205.17    466    340  28693.9493

[891 rows x 6 columns]

In [340]:
df_numeric.sum()

Survived      342.0000
Pclass       2057.0000
Age         21205.1700
SibSp         466.0000
Parch         340.0000
Fare        28693.9493
dtype: float64

In [341]:
df_numeric.var()

Survived       0.236772
Pclass         0.699015
Age          211.019125
SibSp          1.216043
Parch          0.649728
Fare        2469.436846
dtype: float64

Useful summary methods for categorical columns
While we often seem focused on numeric data, in addition to .mode() there are a couple more descriptive statics we can use for categorical data:

Unique entries in categorical column

In [342]:
titanic_train_df["Embarked"].unique()

<ArrowStringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

It'd be good to know the breakdown of the counts in each class: Series.value_counts()

In [343]:
titanic_train_df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

Step 12: Transforming Series and DataFrames
Sometimes we want to do more than simple pre-defined aggregations. Want to implement our own functions on pandas data structures.

Series.map()
Series.apply()
DataFrame.apply()
 
Series.map()
Used for substituting each value in a Series with another value, that may be derived from:

a dict
a mapping function
Returns a new object. This can be a Series or a DataFrame depending on the form of the function. Let's create a new Series to see how this works:

In [344]:
orig_series = pd.Series([2,5,8], index = ['A', 'B', 'C'])
orig_series

A    2
B    5
C    8
dtype: int64

Creating the mapping dictionary and then applying it to our Series.

In [345]:
dict_mapper = {2: 2.5, 5: 7.2, 8: 3.9}
orig_series.map(dict_mapper)

A    2.5
B    7.2
C    3.9
dtype: float64

We can also define a function that applies a numeric transformation and use the .map() method to transform each value in the Series accordingly.

In [346]:
def func(x):
    return 2*x
orig_series.map(func)

A     4
B    10
C    16
dtype: int64

In general, you would use the .map() method for more complex mappings. A simple arithmetic operation like this can be accomplished via using Pandas vectorization implicitly (i.e., just multiply the Series directly by a constant).

In [347]:
2*orig_series

A     4
B    10
C    16
dtype: int64

A more interesting use-case might be when you create mappings for binning continuous data using conditional logic. Here we define a function that checks whether a value for a paid Fare lies in a range and then returns a string denoting what bin that Fare belongs to:

In [348]:
def bin_fare(input):
    if input <= 10:
        return 'Low Fare'
    elif (input > 10) & (input <= 40):
        return 'Medium Fare'
    elif input > 40:
        return 'High Fare'

Applying this function to our Fare data in the titanic dataset yields the binning:

In [349]:
df_numeric['Fare'].map(bin_fare)

0         Low Fare
1        High Fare
2         Low Fare
3        High Fare
4         Low Fare
          ...
886    Medium Fare
887    Medium Fare
888    Medium Fare
889    Medium Fare
890       Low Fare
Name: Fare, Length: 891, dtype: str

In [350]:
df_numeric

     Survived  Pclass   Age  SibSp  Parch     Fare
0           0       3  22.0      1      0   7.2500
1           1       1  38.0      1      0  71.2833
2           1       3  26.0      0      0   7.9250
3           1       1  35.0      1      0  53.1000
4           0       3  35.0      0      0   8.0500
..        ...     ...   ...    ...    ...      ...
886         0       2  27.0      0      0  13.0000
887         1       1  19.0      0      0  30.0000
888         0       3   NaN      1      2  23.4500
889         1       1  26.0      0      0  30.0000
890         0       3  32.0      0      0   7.7500

[891 rows x 6 columns]

Series.apply():
Applies function elementwise to Series:

Only applies functions
Can do what map does w/ functions
Can use functions that simply return a Series or even DataFrames

In [351]:
orig_series

A    2
B    5
C    8
dtype: int64

In [352]:
# did this with map. map is faster for this.

orig_series.apply(func)

A     4
B    10
C    16
dtype: int64

Series.apply() really shines when you want to do something a little more complicated.

For each element in original Series, compute powers of elements up to some order. Return these powers as a series.

In [353]:
# this returns a series [x, x**2, x**3,...up to highest order] for each value
def new_func(x, highest_order = 5):
    
    polynomial_series = pd.Series({'Order ' + str(n+1): x**(n+1) for n in range(highest_order)})
    
    return polynomial_series

Using the .apply() method with new_func, Pandas will run through each element of the original series:

for each, element return a series of the powers from order 1 to order 5
combine the series of powers for each element into a DataFrame

In [354]:
orig_series

A    2
B    5
C    8
dtype: int64

In [355]:
# start with a Series. End up with a DataFrame.
orig_series.apply(new_func)

   Order 1  Order 2  Order 3  Order 4  Order 5
A        2        4        8       16       32
B        5       25      125      625     3125
C        8       64      512     4096    32768

DataFrame.apply()
As an extension of series.apply(), there is DataFrame.applu(). Takes in entire columns (or rows) of dataframe into function and applies transformations:

Transformations can be applied column-wise or row-wise.
The function can return a number, a Series, or a Dataframe.
As such the DataFrame.apply() method is pretty useful, flexible, and is capable of complex transformations.

Let's see an example. Suppose, for some reason we want the sum of the squares of all entries in the Age and Fares column respectively. Then we want to log transform the result for each column.

The function below breaks this down in steps. Each function is designed to accept a Series (representing a given column). Then we square each entry in the column and then take the sum of these squares. Finally, the log of this sum of squares is computed. Thus if the function takes in the data in the Age column (a Series) it will return a single value representing the log-squared-sum.

In [356]:
def log_sq_trans(x):
    x_sq = x**2
    summed_sq = np.sum(x_sq)
    logsquaredsum = np.log(1 + summed_sq)
    
    return logsquaredsum

Now we subset the DataFrame on Age and Fare and apply this function to the DataFrame. The .apply() method then takes in each column (Age and Fare) and computes the log-sum-squared for each. The axis = 0 (the default argument) ensures that the Series being accepted by the function are columns.

In [357]:
# axis = 0: applies function to each column 
df_numeric[['Age', 'Fare']].apply(log_sq_trans, axis = 0)

Age     13.567347
Fare    14.953941
dtype: float64

If for some reason you wanted to have the function accept the rows as argument (i.e., add the squares of Age and Fare for each row and log transforms the result), then you could just change to axis = 1.

In [358]:
df_numeric[['Age', 'Fare']].apply(log_sq_trans, axis = 1)

0      6.287045
1      8.783597
2      6.606387
3      8.305388
4      7.163019
         ...
886    6.801283
887    7.140453
888    6.311558
889    7.363280
890    6.989393
Length: 891, dtype: float64